version: '2'
 
services:
  mysql:
    image: mysql
    container_name: docker-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"

# OPTIONAL TO MOUNT EXTERNAL VOLUME
#    volumes:
#     - /storage/docker/mysql-datadir:/var/lib/mysql
